//
//  AutoReportGlobalUIView.swift
//  native-swiftui-ios-sample-application
//
//  Created by Sabry, Ahmad on 24.01.23.
//

import SwiftUI
import Dynatrace

struct AutoReportGlobalUIView: View {
    @State private var txtError = ""
    @State private var txtInformation =  "Standalone error (not bound to a specific user action)\n https://www.dynatrace.com/support/help/shortlink/ios-oneagent-sdk#report-error\nWith reportError, you can report a specific event as an error event.\nThere are two options for reporting an error event:\nReport it as part of an action (either a custom action or an autogenerated user action)\nReport it as a standalone error, which is generated as a global event that is not tied to a specific action\nReported errors (both standalone and \"attached\" to a user action) are displayed on the user session details page and multidimensional User action analysis page. Reported errors that are part of a user action are also displayed in the user action waterfall analysis.\nYou can report an error with an error code, an exception, or an NSError."
    var body: some View {
        VStack{
            Form{
                Section(){
                    HStack{
                        TextField("User action error", text: $txtError)
                    }
                  
                }
                Section(){
                    Button("Report global error", action: {
                        
                            DTXAction.reportError(withName:  txtError , error: NSError(domain: "Global issue", code: 007, userInfo: nil))
                   
                    })
                }
               
            }
            InformationView( text: txtInformation)

        } .uiKitOnAppear(Self.self)
    }
}

struct AutoReportGlobalUIView_Previews: PreviewProvider {
    static var previews: some View {
        AutoReportGlobalUIView()
    }
}
